# Generated by Django 5.0 on 2024-02-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0003_clientavgmigrationtime_proxyavgmigrationtime"),
    ]

    operations = [
        migrations.CreateModel(
            name="ControllerAvgMigrationTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="client",
            name="is_test",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="proxy",
            name="is_test",
            field=models.BooleanField(default=True),
        ),
    ]
