# Generated by Django 5.0 on 2024-02-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0004_controlleravgmigrationtime_client_is_test_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="assignment_time",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="client",
            name="is_censor_agent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="proxy",
            name="blocked_at",
            field=models.IntegerField(default=0),
        ),
    ]
