# Generated by Django 5.0 on 2024-02-08 00:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "assignments",
            "0005_assignment_assignment_time_client_is_censor_agent_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="flagged",
            field=models.BooleanField(default=False),
        ),
    ]
