# Generated by Django 5.0 on 2024-02-08 04:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0008_proxy_deactivated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChartConnectedUsersRatio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField()),
                ("creation_time", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ChartNonBlockedProxyCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.IntegerField()),
                ("creation_time", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ChartNonBlockedProxyRatio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField()),
                ("creation_time", models.IntegerField()),
            ],
        ),
    ]
