# Generated by Django 5.0 on 2024-02-08 04:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "assignments",
            "0009_chartconnectedusersratio_chartnonblockedproxycount_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="is_expired",
            field=models.BooleanField(default=False),
        ),
    ]
