# Generated by Django 5.0 on 2024-02-08 04:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0010_assignment_is_expired"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="request_count",
            field=models.IntegerField(default=0),
        ),
    ]
