# Generated by Django 5.0 on 2024-02-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0011_client_request_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="known_blocked_proxies",
            field=models.IntegerField(default=0),
        ),
    ]
