# Generated by Django 5.0 on 2024-02-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0012_client_known_blocked_proxies"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="creation_time",
            field=models.IntegerField(default=0),
        ),
    ]
